# Generated by Django 5.2.7 on 2025-12-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Youtube link, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.URLField(default='https://placehold.co/600x400'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(help_text='Enter the lesson content or HTML here'),
        ),
    ]
