# Generated by Django 5.2.7 on 2025-12-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='option_a',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='option_b',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='option_c',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_question',
            field=models.CharField(blank=True, help_text='Enter a quiz question for this lesson', max_length=300, null=True),
        ),
    ]
