# Generated by Django 5.2.7 on 2025-12-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_file',
            field=models.FileField(blank=True, help_text='Upload PDF, PPT, or ZIP', null=True, upload_to='lesson_files/'),
        ),
    ]
