# Generated by Django 5.2.7 on 2025-12-29 09:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_profile_title_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Write your lesson and paste diagrams here', null=True),
        ),
    ]
